[package]
name = "bevy_easy_portals"
version = "0.2.2"
edition = "2021"
description = "Bevy plugin for easy-to-use portals."
keywords = ["bevy", "gamedev"]
categories = ["game-development"]
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/chompaa/bevy_easy_portals"
documentation = "https://docs.rs/bevy_easy_portals"
exclude = [".github"]

[dependencies.bevy]
version = "0.14"
default-features = false
features = ["bevy_core_pipeline", "bevy_pbr", "bevy_render"]

[dev-dependencies.bevy]
version = "0.14"
default-features = false
features = [
    "bevy_core_pipeline",
    "bevy_pbr",
    "bevy_render",
    "tonemapping_luts",
    "x11",
]

[features]
default = []
gizmos = ["bevy/bevy_gizmos"]

[lints.clippy]
too_many_arguments = "allow"
type_complexity = "allow"

[package.metadata.docs.rs]
all-features = true

[[example]]
name = "basic"

[[example]]
name = "mirror"
